CREATE TABLE company (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    api_key_hash VARCHAR(255) NOT NULL,
    callback_url VARCHAR(1000) NOT NULL,

    CONSTRAINT uk_company_name UNIQUE (name),
    CONSTRAINT uk_company_api_key_hash UNIQUE (api_key_hash)
);

INSERT INTO company (
    name,
    api_key_hash,
    callback_url
) VALUES (
    'Minova Heizöl GmbH',
    'demo-api-key-hash',
    'http://localhost:8081/api/dispo/callback'
)
ON CONFLICT (name) DO NOTHING;

ALTER TABLE order_snapshot
    ADD COLUMN company_id BIGINT;

UPDATE order_snapshot
SET company_id = (
    SELECT id
    FROM company
    WHERE name = 'Minova Heizöl GmbH'
)
WHERE company_id IS NULL;

ALTER TABLE order_snapshot
    ALTER COLUMN company_id SET NOT NULL;

ALTER TABLE order_snapshot
    DROP CONSTRAINT uk_order_snapshot_external_order_id;

ALTER TABLE order_snapshot
    ADD CONSTRAINT fk_order_snapshot_company
        FOREIGN KEY (company_id)
        REFERENCES company(id);

ALTER TABLE order_snapshot
    ADD CONSTRAINT uk_order_snapshot_company_external_order_id
        UNIQUE (company_id, external_order_id);

CREATE INDEX idx_order_snapshot_company_id
    ON order_snapshot(company_id);