spring:
  config:
    import: optional:file:.env[.properties]

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/heizoel_backend}
    username: ${DB_USERNAME:heizoel}
    password: ${DB_PASSWORD:heizoel}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false

server:
  servlet:
    session:
      cookie:
        secure: true

heizoel:
  confirmation:
    frontend-url: ${FRONTEND_URL}
    sms-provider-url: ${SMS_PROVIDER_URL}
    whatsapp-provider-url: ${WHATSAPP_PROVIDER_URL}

logging:
  level:
    root: info
    org.hibernate.SQL: warn
    org.hibernate.orm.jdbc.bind: warn
